name: Daily Commit

on:
  schedule:
    - cron: '0 3,9,15,21 * * *'  # 每6小時 commit 一次
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Git Identity
        run: |
          git config user.name "Junwu0615"
          git config user.email "74244029+Junwu0615@users.noreply.github.com"
          # git config user.email "Junwu0615@users.noreply.github.com"

      - name: Add Updates
        run: |
          echo "$(date)" > date.txt
          echo "Random: $RANDOM $(date)" >> log.txt

      - name: Commit And Push
        run: |
          git add date.txt
          git commit -m "Daily update: $(date)" || echo "No changes to commit"
          git push origin main
